server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jingxishop?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 970116hz
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      naming:
        implicitStrategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physicalStrategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5Dialect
  flyway:
    locations: ["classpath:db/migration"]